### ISSUE TITLE
Meteor 1.3 - Unable to run 'meteor test' with huttonr:bootstrap3 + bootstrap-settings.json file

### ISSUE THREAD

**Issue by waitem** [huttonr/bootstrap3#17]
Hi and thanks very much for providing this package, which I have been using with Meteor 1.2.

I've just upgraded to Meteor 1.3 and unfortunately I have discovered that I am unable to run any tests using the `meteor test` when huttonr:bootstrap3 package is installed AND a bootstrap-settings.json file exists.

The problem is simple to reproduce (I'm running Ubuntu Linux 14.04 LTS). Please see the instructions and output below.

Many thanks in advance for looking at this issue or suggesting a workaround.

`
meteor create meteor-huttonr-bootstrap3-test
cd meteor-huttonr-bootstrap3-test
meteor add practicalmeteor:mocha
meteor test   --driver-package practicalmeteor:mocha --port 3100  # this works fine

meteor add huttonr:bootstrap3
meteor test  --driver-package practicalmeteor:mocha --port 3100  # this still works fine (no bootstrap-settings.json yet)

mkdir client/stylesheets
touch client/stylesheets/bootstrap.json
meteor test  --driver-package practicalmeteor:mocha --port 3100  # Throws an error:

/home/me/.meteor/packages/less/.2.5.6.rqntqf++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
AssertionError: "undefined" === false
    at ImportScanner._combineFiles (/tools/isobuild/import-scanner.js:154:12)
    at /tools/isobuild/import-scanner.js:140:14
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:119:11)
    at /tools/isobuild/compiler-plugin.js:756:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:726:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:910:8)
    at /tools/isobuild/bundler.js:677:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:668:18)
    at /tools/isobuild/bundler.js:2509:14
    at /tools/isobuild/bundler.js:2599:20
    at Array.forEach (native)
    at Function._.each._.forEach (/home/me/.meteor/packages/meteor-tool/.1.3.0_3.61500n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2598:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2490:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
`

**Comment by huttonr** [comment]
I have not yet tested out the `practicalmeteor:mocha` testing driver but I'll check this out as soon as possible.

Thank you for the bug report.

**Comment by smilansky** [comment]
+1

**Comment by pipewrk** [comment]
I'm having this problem simply running meteor and not tests. I'll post another issue

**Comment by smilansky** [comment]
Fixed after updating to meteor 1.3.2.2

**Comment by huttonr** [comment]
@waitem Can you verify that this is fixed for you after upgrading to Meteor 1.3.2.2?

**Comment by waitem** [comment]
Yes, this is now working again after upgrading to 1.3.2.2
Many thanks for your assistance!

**Comment by huttonr** [comment]
Excellent news.
