### ISSUE TITLE
Error after upgrading to Meteor 1.3.2-rc.5

### ISSUE THREAD

**Issue by pipewrk** [huttonr/bootstrap3#18]
Hi, this is similar to #17 except it only happens when meteor is updated to 1.3.2-rc-5 when attempting to combat https://github.com/meteor/meteor/issues/6714. We simply running `meteor run` and it throws this error

```
  .meteor/packages/coffeescript/.1.0.17-rc.5.1u1ahm1++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
        throw error;
              ^
  Error: Attempting to combine different files:
  { type: 'js',
    data: <Buffer 2f 2f 20 54 68 65 73 65 20 73 74 79 6c 65 73 20 68 61 76 65 20 61 6c 72 65 61 64 79 20 62 65 65 6e 20 61 70 70 6c 69 65 64 20 74 6f 20 74 68 65 20 64 6f ...>,
    sourcePath: 'client/less/1-Frameworks/bootstrap-settings.json',
    servePath: '/client/stylesheets/bootstrap/bootstrap.generated.css',
    hash: 'bf5916be0fd88667452ec454871f4856bca634d3',
    sourceMap: undefined,
    lazy: true,
    bare: false,
    mainModule: false,
    imported: false,
    installPath: 'client/less/1-Frameworks/bootstrap-settings.json' }
  { type: 'js',
    data: <Buffer 4d 65 74 65 6f 72 2e 5f 62 6f 6f 74 73 74 72 61 70 53 65 74 74 69 6e 67 73 46 69 6c 65 4c 6f 61 64 65 64 20 3d 20 74 72 75 65 3b 0a 69 66 20 28 4d 65 74 ...>,
    sourcePath: 'client/less/1-Frameworks/bootstrap-settings.json',
    servePath: '/client/lib/bootstrap/bootstrap.generated.js',
    hash: 'ea714bcffd9feb404af15da8baf24afe316f7216',
    sourceMap: undefined,
    lazy: false,
    bare: false,
    mainModule: false,
    imported: true,
    installPath: 'client/less/1-Frameworks/bootstrap-settings.json' }

      at checkProperty (/tools/isobuild/import-scanner.js:198:15)
      at ImportScanner._combineFiles (/tools/isobuild/import-scanner.js:187:35)
      at /tools/isobuild/import-scanner.js:177:14
      at Array.forEach (native)
      at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:148:11)
      at /tools/isobuild/compiler-plugin.js:825:15
      at Array.forEach (native)
      at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:796:19)
      at ClientTarget._emitResources (/tools/isobuild/bundler.js:913:8)
      at /tools/isobuild/bundler.js:684:12
      at /tools/utils/buildmessage.js:359:18
      at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
      at /tools/utils/buildmessage.js:352:34
      at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
      at /tools/utils/buildmessage.js:350:23
      at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
      at Object.enterJob (/tools/utils/buildmessage.js:324:26)
      at ClientTarget.make (/tools/isobuild/bundler.js:675:18)
      at /tools/isobuild/bundler.js:2474:14
      at /tools/isobuild/bundler.js:2563:20
      at Array.forEach (native)
      at Function._.each._.forEach (~/.meteor/packages/meteor-tool/.1.3.2-rc.5.xhhcrq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
      at /tools/isobuild/bundler.js:2562:7
      at /tools/utils/buildmessage.js:271:13
      at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
      at /tools/utils/buildmessage.js:264:29
      at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
      at /tools/utils/buildmessage.js:262:18
      at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
      at /tools/utils/buildmessage.js:253:23
      at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
      at Object.capture (/tools/utils/buildmessage.js:252:19)
      at Object.exports.bundle (/tools/isobuild/bundler.js:2455:31)
      at /tools/runners/run-app.js:591:36
      at Function.run (/tools/tool-env/profile.js:489:12)
      at bundleApp (/tools/runners/run-app.js:581:34)
      at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
      at AppRunner._fiber (/tools/runners/run-app.js:887:28)
      at /tools/runners/run-app.js:411:12
```

**Comment by huttonr** [comment]
@jasonnathan Is this fixed for you now after upgrading to Meteor 1.3.2.2?

**Comment by pipewrk** [comment]
@huttonr I upgraded to 1.3.2.4 and it is fixed, didn't get to test the ones in between

**Comment by huttonr** [comment]
Good news.
