### ISSUE TITLE
Cannot find module 'less'

### ISSUE THREAD

**Issue by vqc** [huttonr/bootstrap3#22]
Not sure what's triggering this error here. 

Meteor 1.2.1
I have less package (2.5.1) installed, but I don't think that's an issue here.

```
W20160701-15:35:08.005(-7)? (STDERR) Error: Cannot find module 'less'
W20160701-15:35:08.005(-7)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20160701-15:35:08.005(-7)? (STDERR)     at Function.Module._load (module.js:280:25)
W20160701-15:35:08.006(-7)? (STDERR)     at Module.require (module.js:364:17)
W20160701-15:35:08.006(-7)? (STDERR)     at require (module.js:380:17)
W20160701-15:35:08.006(-7)? (STDERR)     at Object.Npm.require (/Users/vqc/Projects/vetsharehospital/.meteor/local/build/programs/server/boot.js:150:18)
W20160701-15:35:08.006(-7)? (STDERR)     at Package (plugin/bootstrap3.js:4:21)
W20160701-15:35:08.006(-7)? (STDERR)     at /Users/vqc/Projects/vetsharehospital/.meteor/local/build/programs/server/packages/huttonr_bootstrap3.js:443:4
W20160701-15:35:08.006(-7)? (STDERR)     at /Users/vqc/Projects/vetsharehospital/.meteor/local/build/programs/server/packages/huttonr_bootstrap3.js:450:3
W20160701-15:35:08.006(-7)? (STDERR)     at /Users/vqc/Projects/vetsharehospital/.meteor/local/build/programs/server/boot.js:242:10
W20160701-15:35:08.007(-7)? (STDERR)     at Array.forEach (native)
```

**Comment by huttonr** [comment]
I haven't been able to reproduce this, can you make reproduction repo?

**Comment by vqc** [comment]
Ended up not needing this package. (Found a way to fix a problem without needing to upgrade to Meteor 1.2 and switching bootstrap packages.)
